In [1]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
import numpy as np

# Sample data
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])

# Standardize the data (important for PCA)
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

# Initialize PCA with desired number of components
pca = PCA(n_components=2) # Reduce to 2 principal components

# Fit PCA to the scaled data and transform it
principal_components = pca.fit_transform(scaled_data)

print("Original data shape:", data.shape)
print("Transformed data shape:", principal_components.shape)
print("Explained variance ratio:", pca.explained_variance_ratio_)

Original data shape: (4, 3)
Transformed data shape: (4, 2)
Explained variance ratio: [1.00000000e+00 1.23259516e-32]


In [2]:
principal_components

array([[-2.32379001e+00, -2.83777291e-16],
       [-7.74596669e-01,  5.26712619e-17],
       [ 7.74596669e-01, -5.26712619e-17],
       [ 2.32379001e+00, -2.48663116e-16]])

In [ ]:
# derive this using numpy
# standardise the data

data_s = data - data.mean(axis=0, keepdims=True)
print(data_s)
data_s = data_s / np.std(data_s, axis=0)
print(data_s)

print(np.mean(data_s, axis=0))
print(np.std(data_s, axis=0))

[[-4.5 -4.5 -4.5]
 [-1.5 -1.5 -1.5]
 [ 1.5  1.5  1.5]
 [ 4.5  4.5  4.5]]
[[-1.34164079 -1.34164079 -1.34164079]
 [-0.4472136  -0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079  1.34164079]]
[0. 0. 0.]
[1. 1. 1.]


In [16]:
# eigen values and eigen vectors
data_cov = np.cov(data_s, ddof=1, rowvar=False)
eigen_values, eigen_vectors = np.linalg.eig(data_cov)
print(eigen_values)
print(eigen_vectors)

[ 4.00000000e+00 -2.46519033e-32 -1.62301832e-16]
[[ 5.77350269e-01 -1.55739853e-17  5.16053913e-01]
 [ 5.77350269e-01 -7.07106781e-01 -8.05992529e-01]
 [ 5.77350269e-01  7.07106781e-01  2.89938616e-01]]


In [17]:
sorted_indices = np.argsort(eigen_values)[::-1]
sorted_eigen_values = eigen_values[sorted_indices]
sorted_eigen_vectors = eigen_vectors[:, sorted_indices]

In [ ]:
# 2 Principal components
k = 2
transformed_data = np.matmul(data_s, sorted_eigen_vectors[:, :k])
print(f"{transformed_data=}")

transformed_data=array([[-2.32379001e+00, -1.11122743e-16],
       [-7.74596669e-01, -6.09642446e-17],
       [ 7.74596669e-01,  6.09642446e-17],
       [ 2.32379001e+00,  1.11122743e-16]])


In [25]:
print(f"{principal_components=}")
assert np.allclose(transformed_data, principal_components)

principal_components=array([[-2.32379001e+00, -2.83777291e-16],
       [-7.74596669e-01,  5.26712619e-17],
       [ 7.74596669e-01, -5.26712619e-17],
       [ 2.32379001e+00, -2.48663116e-16]])
